language: node_js

node_js:
  - "0.11"
  - "0.10"

matrix:
  fast_finish: true

before_script:
  - ln -s ../ ./node_modules/jscs-jsdoc

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/056980f855fa83cb5fd6
    on_success: change
    on_failure: always
    on_start: false
